name: Application jobs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/asdf-setup

      - name: pnpm install
        run: pnpm install

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: $(pnpm store path)
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: pnpm lint
        run: pnpm lint

      - name: Upload node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/asdf-setup

      - name: pnpm lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/asdf-setup

      - name: pnpm test
        run: pnpm test
