name: Application jobs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v4.0.0
      - name: pnpm install
        run: pnpm install
      - name: pnpm lint
        run: pnpm lint
