name: Build docker image

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/asdf-setup
      - uses: ./.github/actions/pnpm

      - name: pnpm build
        uses: pnpm build

      - uses: actions/cache@v4
        id: cache-build
        with:
          path: ./dist
          key: dist-${{ github.sha }}
          restore-keys: dist-

  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/cache@v4
        id: restore-build
        with:
          path: ./dist
          key: dist-${{ github.sha }}

      - name: Determine tag
        id: get-tag
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG="${{ github.ref_name }}"
          else
            TAG=$(git fetch --tags && git tag -l 'v*.*.*' | sort -V | tail -n 1)
          fi
          echo "Using tag: $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/themeteorain/piano-staff/frontend:latest
            ghcr.io/themeteorain/piano-staff/frontend:${{ steps.get-tag.outputs.tag }}
