name: Release Please

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.PROJECT_TOKEN }}

  update-manifest:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - name: Get version from tag
        id: get-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update manifest.json
        run: |
          jq --arg version "$VERSION" '.version = $version' public/manifest.json > tmp.json && mv tmp.json public/manifest.json

      - name: Commit manifest update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add public/manifest.json
          git commit -m "chore(manifest): update version to $VERSION"
          git push
