on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      prs_created: ${{ steps.release.outputs.prs_created }}
      pr: ${{ steps.release.outputs.pr }}
      prs: ${{ steps.release.outputs.prs }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.PROJECT_TOKEN }}
          release-type: node
      - name: debug outputs
        run: |
          echo "PRs created: ${{ steps.release.outputs.prs_created }}"
          echo "PR: ${{ steps.release.outputs.pr }}"
          echo "PRs: ${{ steps.release.outputs.prs }}"
          echo "Version: ${{ steps.release.outputs.version }}"

  update-manifest:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.prs_created == 'true' }}
    steps:
      - name: Debug outputs
        run: |
          echo "PR: ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}"
          echo "Version: ${{ needs.release-please.outputs.version }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}
          fetch-depth: 0

      - name: Update public/manifest.json
        run: |
          jq --arg version "${{ needs.release-please.outputs.version }}" '.version = $version' public/manifest.json > tmp.json && mv tmp.json public/manifest.json

      - name: Commit and push updated manifest.json
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add public/manifest.json
          git commit --amend --no-edit
          git pull --rebase origin ${{ fromJson(needs.release-please.outputs.pr).headBranchName }}
          git push
